### ISSUE TITLE
Lo intentamos de nuevo?

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcas-s3-evaluacion-intermedia-veronicabautista#1]
Te dejo un guión a ver si te sirve:

1. Pasar el array por props a App
2. Desde App, en un UL, usar map para convertir el array de datos en un array de jsx, usando LI
3. Pasar por props los datos al componente de dicha de pokemoon
***
BONUS: Una vez hecho esto:  

1. Crear un componente PokemonList que pinte solo la lista de Pokemons, esto es: el ul, los li (con el atributo key="") y el componente de la card
2. Crear un componente PokemonCard para el componente de la card.

**Comment by oneeyedman** [comment]
Ole! Si te animas a terminar el bonus dímelo. 

PD. mira que la carpeta components está fuera de src

**Comment by veronicabautista** [comment]
Bonus realizado! A falta de estilos. 
![computer-cat](https://user-images.githubusercontent.com/39790135/43737166-a9892702-99c0-11e8-8c97-91442ff1aa84.jpg)

**Comment by veronicabautista** [comment]
Aprovechando mi cacao de esta mañana con recoger el valor del buscador, lo he repetido en este ejercicio, y funciona :dancer:
